<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="C:\Users\eduar\.nuget\packages\toonnet\1.0.4\contentFiles\any\net10.0\ToonNet.png" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
		<None Remove="Context.txt" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Context.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="LibGit2Sharp" Version="0.31.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="ToonNet" Version="1.0.4" />
	</ItemGroup>

</Project>
